export const GEMINI_SENTIMENT_ANALYSIS_MODEL = 'GEMINI_SENTIMENT_ANALYSIS_MODEL';
export const GEMINI_ADVISORY_FEEDBACK_MODEL = 'GEMINI_ADVISORY_FEEDBACK_MODEL';
export const GEMINI_FIND_LANGUAGE_MODEL = 'GEMINI_FIND_LANGUAGE_MODEL';
