export const GEMINI_SENTIMENT_ANALYSIS_MODEL = 'GEMINI_SENTIMENT_ANALYSIS_MODEL';
export const GEMINI_REPLY_MODEL = 'GEMINI_REPLY_MODEL';
export const GEMINI_FIND_LANGUAGE_MODEL = 'GEMINI_FIND_LANGUAGE_MODEL';
